version: "3"

services:
  flask_restful_swagger:
    build:
      context: .
      dockerfile: development/Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - development.env
    volumes:
      - ${HOME}/.ssh:/home/user/.ssh
      - ${HOME}/.gitconfig:/home/user/.gitconfig
      - ${HOME}/.gitconfig_global:/home/user/.gitconfig_global
      - ./:/app
    command: >
      ./flask_restful_swagger/container_boot.sh
