#!/bin/bash

set -eo pipefail

# Get the current branch name
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "develop" ]]; then

  exec < /dev/tty
  echo "WARNING: You have just merged code into a protected branch."
  read -r -p "Type 'yes' to confirm: " confirm

  if [[ $confirm == "yes" ]]; then

    bash scripts/commander.sh lint
    bash scripts/commander.sh test
    bash scripts/commander.sh sectest

  else

    git reset --soft 'HEAD@{1}'
    echo "Aborted Commit"
    exit 127

  fi

fi
