#!/bin/bash

set -eo pipefail

clean() {

  bash scripts/commander.sh lint

}

main() {

  BRANCH=$(git symbolic-ref --short HEAD)
  if [[ "$BRANCH" == "master" || "$BRANCH" == "develop" ]]; then

     exec < /dev/tty
     echo "WARNING: You are on a protected branch!"
     read -r -p "Type 'yes' to confirm: " confirm
     [[ $confirm != "yes" ]] && echo 'ABORTED' && exit 127

    clean
    bash scripts/commander.sh test
    bash scripts/commander.sh sectest

  else

    clean

  fi

  if [[ -n "$(git diff)" ]]; then

    git status

    exec < /dev/tty
    echo -e "\nWARNING: You have uncommitted changes, that could be a result of yapf formatting."
    read -r -p "Type 'yes' to confirm you wish to proceed with this commit: " confirm
    [[ $confirm != "yes" ]] && echo 'ABORTED' && exit 127

    exit 0

  fi

}

main
