#!/bin/bash

set -eo pipefail

bypass() {

  # Bypass Unless GitHooks Are Enabled
  [[ "${GIT_HOOKS}" == "1" ]] && exit 0

  local_branch="$(git rev-parse --abbrev-ref HEAD)"
  protected_branches="${GIT_HOOKS_PROTECTED_BRANCHES}"

  if [[ ! ${local_branch} =~ ${protected_branches} ]]; then
        exit 0
  fi

}

main() {

  bypass

  bash scripts/commander.sh lint-validate
  bash scripts/commander.sh sectest
  bash scripts/commander.sh test
  shellcheck -x scripts/*.sh
  shellcheck -x scripts/common/*.sh

  if [[ -n "$(git diff)" ]]; then

    git status

    exec < /dev/tty
    echo -e "\nWARNING: You have uncommitted changes!"
    read -r -p "Type 'yes' to confirm you wish to proceed with this commit: " confirm
    [[ ${confirm} != "yes" ]] && echo 'ABORTED' && exit 127

    exit 0

  fi

}

main
